### ISSUE TITLE
Creazione richiesta di nuovo progetto pubblico

### ISSUE THREAD

**Issue by AndreaPerrello** [matteosartori/bsod#15]
Un utente può caricare un'idea/richiesta attraverso una form. La form contiene titolo, descrizione, un'immagine dell'oggetto (?). A progetto caricato, qualunque utente può contribuire e partecipare diventando un collaboratore (vedi "Gestione progetto attivo"). Chiunque può invitare altre persone ad aggiungersi (è una notifica di richiesta di contribuzione).

**Comment by lucav48** [comment]
Manca la parte dell'aggiunta dei collaboratori.
